### ISSUE TITLE
Linked Animation Instance Macro

### ISSUE THREAD

**Issue by Maciek-Letowt** [Voidware-Prohibited/ALSXT#29]
I updated my local copy of the repository, but can no longer build in JetBrains Rider 2022.3.2. 
I get build errors.
The messages seem to be pointing to Linked Animation Instance Macro at line 46 of **ALSXTLinkedAnimationInstance.cpp**
`Reference C2338 : see reference to function template instantiation`

Below is the full list of build errors:

```
Building 4 actions with 1 process...
[1/4] Link UnrealEditor-ALSXT.dll cancelled
[2/4] Link UnrealEditor-ALSXT.lib cancelled
[3/4] WriteMetadata MyGameEditor.target cancelled
[4/4] Compile Module.ALSXT.4_of_4.cpp

G:\UE_5.1\Engine\Source\Runtime\Core\Public\Logging\LogMacros.h(63): Error C2338 : Invalid argument(s) passed to FMsg::Logf_Internal

G:\source\repos\MyGame\Plugins\ALSXT\Source\ALSXT\Private\ALSXTLinkedAnimationInstance.cpp(46): Reference C2338 : see reference to function template instantiation 'void FMsg::Logf_Internal<wchar_t[94],FStringView,const TCHAR*,FStringView>(const ANSICHAR *,int32,const FLogCategoryName &,ELogVerbosity::Type,const FmtType (&),FStringView,const TCHAR *,FStringView)' being compiled
        with
        [
            FmtType=wchar_t [94]
        ]

G:\UE_5.1\Engine\Source\Runtime\Core\Public\Misc\AssertionMacros.h(170): Reference C2338 : see reference to function template instantiation 'void UALSXTLinkedAnimationInstance::NativeBeginPlay::<lambda_fe59a0c9bacd3e46cca2d06863412587>::()::<lambda_cf32e40be412dc3c70fe756d60e98d82>::operator ()<FLogCategoryLogOutputDevice,wchar_t[94],FStringView,const TCHAR*,FStringView>(const FLogCategoryLogOutputDevice &,const wchar_t (&)[94],const FStringView &,const TCHAR *const &,const FStringView &) const' being compiled

G:\source\repos\MyGame\Plugins\ALSXT\Source\ALSXT\Private\ALSXTLinkedAnimationInstance.cpp(46): Reference C2338 : see reference to function template instantiation 'RetType DispatchCheckVerify<void,UALSXTLinkedAnimationInstance::NativeBeginPlay::<lambda_fe59a0c9bacd3e46cca2d06863412587>::()::<lambda_cf32e40be412dc3c70fe756d60e98d82>,FLogCategoryLogOutputDevice,wchar_t[94],FStringView,const TCHAR*,FStringView>(InnerType &&,const FLogCategoryLogOutputDevice &,const wchar_t (&)[94],const FStringView &,const TCHAR *const &,const FStringView &)' being compiled
        with
        [
            RetType=void,
            InnerType=UALSXTLinkedAnimationInstance::NativeBeginPlay::<lambda_fe59a0c9bacd3e46cca2d06863412587>::()::<lambda_cf32e40be412dc3c70fe756d60e98d82>
        ]

G:\Programs\VS2022\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): Error MSB3073 : The command "G:\UE_5.1\Engine\Build\BatchFiles\Build.bat MyGameEditor Win64 Development -Project="G:\source\repos\MyGame\MyGame.uproject" -WaitMutex -FromMsBuild" exited with code 6.
Build failed at 8:33:42 PM
```

**Comment by colorindarkness** [comment]
Thanks! Fixed in 6ab7098ffb9bd2219b74ba21e0afe6053bf5c82b. ALSXT is now compatible with 5.1+
